name: "track-pypi-version"

description:
  "Check for updated package on requirements.txt from PyPI, update and commit change on requirements.txt file"

branding:
  icon: git-commit
  color: white

inputs:
  compush:
    description: "Specify if commit and push need to be done. Default to true"
    required: false
    default: "true"
  reqfile:
    description: "Path to requirements.txt file. Default to ./requirements.txt"
    required: false
    default: "./requirements.txt"
  backup:
    description: "Make a backup of requirements.txt (set to true). Default to false"
    required: false
    default: "false"

outputs:
  commit:
    description: "'true' if need a commit"

runs:
  using: "node12"
  main: "dist/index.js"
