version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: Check branch
          command: |
            if [ "$CIRCLE_BRANCH" = "release-master" ]; then
                circleci-agent step halt
            fi
      - node/with-cache:
          steps:
            - run: npm install
            # - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test
